version: '3'

services:
  testone:
    build: .
    command: "0.05"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:10001"
        syslog-format: rfc5424
        tag: tester1
  testtwo:
    build: .
    command: "0.05"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:10001"
        syslog-format: rfc5424
        tag: tester2
